# Telekom DE Wi-Fi Calling · Shadowrocket standalone configuration
[General]

[Rule]
DOMAIN-SUFFIX,telekom.de,PROXY
DOMAIN-SUFFIX,telekom.com,PROXY
DOMAIN-SUFFIX,t-mobile.de,PROXY
DOMAIN-SUFFIX,prod.con-telekom.de,PROXY
DOMAIN-SUFFIX,wlan-call.t-mobile.de,PROXY
DOMAIN-SUFFIX,mcc262.pub.3gppnetwork.org,PROXY
FINAL,DIRECT
