# Ultra Mobile / T-Mobile US Wi-Fi Calling · Shadowrocket standalone configuration
[General]

[Rule]
DOMAIN-SUFFIX,ultramobile.com,PROXY
DOMAIN-SUFFIX,ultra.me,PROXY
DOMAIN-SUFFIX,t-mobile.com,PROXY
DOMAIN-SUFFIX,tmomail.net,PROXY
DOMAIN-SUFFIX,t-mobile.akadns.net,PROXY
DOMAIN-SUFFIX,mcc310.pub.3gppnetwork.org,PROXY
DOMAIN-SUFFIX,mcc311.pub.3gppnetwork.org,PROXY
FINAL,DIRECT
